### ISSUE TITLE
Label text on creation pages is basically invisible

### ISSUE THREAD

**Issue by DecafMegalodon** [leggettc13/ChoreTracker2#7]
Examples:
parents/sign_up
chores/new

**Comment by napolij14** [comment]
Something like:

label{
     color: white !important; // some color
}

in the scaffolds.scss(i dont really know priorities of the css files, but this worked)  file will fix most of that, some of the labels arent actually 'label' divs and may need to be put inside a div or manually set color. (inside a div is prob easiest/cleanest/most consistent, and giv that div some attributes)
